from app.llm.graph.state import GraphState


def test_graph_state_keys():
    required = {
        "question",
        "connection_id",
        "connector_type",
        "connection_string",
        "timeout_seconds",
        "max_rows",
        "db",
        "sql",
        "result",
        "generated_sql",
        "retry_count",
        "explanation",
        "llm_provider",
        "llm_model",
        "answer",
        "highlights",
        "suggested_followups",
        "execution_id",
        "execution_time_ms",
        "error",
        "session_id",
        "user_id",
        "user_role",
        "resource_id",
        "employee_id",
        "loaded_history",
        "last_generated_sql",
        "last_result_columns",
        "last_result_preview_rows",
        "action",
        "resolved_question",
        "clarification_reason",
        "clarification_message",
        "clarification_options",
        "event_queue",
    }
    assert required == set(GraphState.__annotations__.keys())
